# Generated by Django 4.2.14 on 2024-07-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("ingredients", models.CharField(max_length=250)),
                (
                    "instructions",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("comments", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "pic",
                    models.ImageField(default="no_picture.jpg", upload_to="recipes/"),
                ),
            ],
        ),
    ]
