# Generated by Django 4.2.14 on 2024-07-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_ingredient_remove_recipe_ingredients_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
    ]
