# Generated by Django 4.2.14 on 2024-07-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_recipe_ingredients"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipeingredient",
            old_name="ingredient",
            new_name="ingredients",
        ),
    ]
