# Generated by Django 4.2.14 on 2024-07-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_recipeingredient_ingredients_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="comments",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
